In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('Dataset/fb.csv')
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [5]:
df.shape

(500, 19)

In [16]:
# paid and unpaid posts
df['Paid'].value_counts()

Paid
0.0    360
1.0    139
Name: count, dtype: int64

In [19]:
# Display page type, like ,comment, share
df[['Type','Post Month','like','comment','share']]

       Type  Post Month    like  comment  share
0     Photo          12    79.0        4   17.0
1    Status          12   130.0        5   29.0
2     Photo          12    66.0        0   14.0
3     Photo          12  1572.0       58  147.0
4     Photo          12   325.0       19   49.0
..      ...         ...     ...      ...    ...
495   Photo           1    53.0        5   26.0
496   Photo           1    53.0        0   22.0
497   Photo           1    93.0        4   18.0
498   Photo           1    91.0        7   38.0
499   Photo           1    91.0        0   28.0

[500 rows x 5 columns]

In [20]:
# avg number of likes in september

In [23]:
# posts which are link
li = df.groupby('Type')
li.get_group('Link')

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
41,138895,Link,1,12,6,3,1.0,18480,28438,517,366,460,12078,6752,319,6,187.0,18.0,211
43,138353,Link,1,12,5,3,1.0,2645,4270,134,109,170,2330,1377,101,7,29.0,10.0,46
45,138353,Link,1,12,4,3,1.0,7968,13023,206,158,223,6734,3492,138,4,57.0,10.0,71
47,138353,Link,1,12,3,2,0.0,1925,3481,97,83,126,2307,1180,77,6,18.0,8.0,32
49,138353,Link,1,12,2,2,0.0,1536,3094,84,76,99,2903,1407,76,1,12.0,1.0,14
86,137177,Link,1,11,4,3,0.0,21176,54779,330,228,329,13858,5248,185,2,130.0,31.0,163
136,136393,Link,1,10,5,10,0.0,4664,9463,204,182,251,7196,3324,173,0,32.0,16.0,48
140,136013,Link,1,10,4,3,0.0,68992,229733,1032,975,1345,17842,8032,635,15,143.0,44.0,202
149,135713,Link,1,10,6,11,1.0,3616,6887,111,90,118,4263,2138,93,0,24.0,11.0,35
344,117764,Link,1,5,1,2,0.0,12540,19301,344,322,396,16914,11008,289,3,46.0,14.0,63
372,113028,Link,1,4,5,7,1.0,35360,45260,339,325,477,9105,5472,156,7,38.0,11.0,56
403,107907,Link,1,4,2,6,0.0,70912,94172,1374,1106,1267,42338,27232,788,1,379.0,40.0,420
408,106928,Link,1,4,6,4,0.0,34192,42092,338,322,389,22907,16464,230,1,36.0,7.0,44
425,102112,Link,3,3,1,3,0.0,6876,10885,282,245,337,9403,5752,259,2,68.0,15.0,85
430,100732,Link,1,3,7,14,0.0,2933,5144,24,23,26,3972,2012,19,0,6.0,0.0,6
438,98195,Link,2,3,6,6,0.0,5730,10083,103,71,97,8964,4830,92,2,32.0,15.0,49
470,91437,Link,1,2,3,13,0.0,9356,14986,448,381,505,13919,8460,392,4,114.0,13.0,131
477,86909,Link,1,1,6,4,0.0,39600,7927,572,496,581,12522,8176,167,1,101.0,5.0,107
481,86491,Link,1,1,4,4,1.0,4938,7910,66,63,70,6625,3804,59,0,5.0,2.0,7
485,86491,Link,1,1,2,2,0.0,5168,8371,66,59,71,7041,3996,58,0,12.0,2.0,14
492,85979,Link,1,1,5,11,0.0,45920,5808,753,655,763,15766,10720,220,0,128.0,9.0,137

In [26]:
sh = li.get_group('Video')
sh

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
55,138329,Video,1,11,6,2,1.0,16416,31950,459,411,539,21436,9568,363,2,65.0,14.0,81
71,137893,Video,1,11,5,3,1.0,100768,220447,2101,1735,2331,59658,18880,885,17,449.0,84.0,550
74,137893,Video,1,11,3,11,0.0,13544,30235,517,458,667,26622,11760,447,2,99.0,13.0,114
183,134879,Video,1,9,2,10,0.0,30624,56950,2080,1956,3253,32033,15744,1376,6,345.0,121.0,472
243,130791,Video,1,7,3,11,1.0,21872,40413,3872,3822,7327,24667,12920,2218,18,315.0,76.0,409
277,126424,Video,1,6,2,13,0.0,139008,277100,1779,1643,2356,107502,38720,1008,23,204.0,44.0,271

In [34]:
#total number of shares for video post
sh['share'].sum()

365.0

In [41]:
# information of posts where likes >200 & shares >30
x = df[(df['like']>200) & (df['share']>30) ]
x

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
26,138458,Status,2,12,5,11,0.0,19552,34143,2806,2531,3420,17748,9824,1779,10,412.0,72.0,494
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
38,138895,Status,2,12,7,9,0.0,17576,33058,5352,5202,6547,23135,11792,4104,11,227.0,31.0,269
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,92079,Photo,1,2,6,13,0.0,158208,453213,2482,2319,3412,81938,20608,1034,9,268.0,36.0,313
468,91651,Photo,1,2,4,12,0.0,15288,31467,1573,1401,2110,28247,13312,1052,5,264.0,36.0,305
476,86909,Photo,1,1,6,10,1.0,37088,10966,2728,2288,3183,66311,34352,2021,7,579.0,47.0,633
480,86909,Photo,2,1,4,11,0.0,11484,20696,1762,1635,2741,8774,5124,722,56,360.0,99.0,515
488,85979,Photo,3,1,7,10,0.0,9700,17442,1407,1271,2007,8872,4876,660,21,277.0,80.0,378

In [48]:
po = df.groupby('Post Month')
nov = po.get_group(11)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
50,138353,Photo,2,11,1,9,0.0,1728,3155,108,65,95,2313,1232,77,1,48.0,9.0,58
51,138329,Photo,1,11,1,3,1.0,25248,40125,726,467,863,16132,8608,451,24,285.0,28.0,337
52,138329,Photo,1,11,7,9,0.0,4894,8899,355,181,264,4914,2712,246,9,202.0,31.0,242
53,138329,Photo,1,11,7,3,0.0,2935,5439,237,182,401,3901,2044,201,4,64.0,19.0,87
54,138329,Photo,1,11,6,10,0.0,2425,4462,260,213,433,3017,1510,175,4,66.0,13.0,83
55,138329,Video,1,11,6,2,1.0,16416,31950,459,411,539,21436,9568,363,2,65.0,14.0,81
56,138329,Photo,1,11,5,11,0.0,5812,10465,343,204,301,4976,2764,240,2,164.0,54.0,220
57,138329,Photo,1,11,5,3,0.0,2545,4846,165,131,167,3675,1901,134,0,40.0,13.0,53
58,138329,Photo,1,11,4,10,0.0,2257,4372,230,173,327,3188,1557,168,3,76.0,11.0,90
59,138329,Photo,1,11,4,3,1.0,27072,84885,421,304,487,35637,9712,263,4,139.0,17.0,160
60,138185,Photo,1,11,3,11,1.0,10940,27951,417,335,591,15066,5100,319,8,101.0,14.0,123
61,138185,Photo,1,11,3,2,1.0,50912,164528,630,513,952,54653,12704,346,8,144.0,10.0,162
62,138185,Photo,1,11,2,10,1.0,28752,47358,802,654,1268,14091,7456,408,10,179.0,13.0,202
63,138185,Photo,1,11,2,3,1.0,27216,81908,541,335,540,26869,7760,315,4,219.0,22.0,245
64,138185,Photo,1,11,1,10,0.0,2352,5234,232,182,258,4101,1761,181,2,60.0,7.0,69
65,138185,Photo,1,11,1,3,0.0,3416,6167,356,298,641,4530,2388,280,19,77.0,23.0,119
66,138185,Photo,1,11,7,11,0.0,2149,4120,197,156,219,3302,1640,161,0,48.0,7.0,55
67,138185,Photo,1,11,7,3,1.0,53456,93790,1576,995,1469,32646,14912,884,20,697.0,70.0,787
68,138185,Photo,1,11,6,11,0.0,2168,3891,211,168,202,2873,1539,171,0,53.0,17.0,70
69,137893,Photo,1,11,6,3,0.0,3102,5939,360,288,512,3537,1780,275,7,84.0,28.0,119
70,137893,Photo,1,11,5,10,1.0,39344,103050,588,460,695,39304,11392,336,7,146.0,9.0,162
71,137893,Video,1,11,5,3,1.0,100768,220447,2101,1735,2331,59658,18880,885,17,449.0,84.0,550
72,137893,Status,3,11,4,11,0.0,9056,16362,1006,847,1153,9562,5180,740,3,226.0,44.0,273
73,137893,Photo,1,11,4,2,1.0,11444,46054,555,418,717,13737,4320,438,14,172.0,47.0,233
74,137893,Video,1,11,3,11,0.0,13544,30235,517,458,667,26622,11760,447,2,99.0,13.0,114
75,137893,Photo,1,11,3,2,1.0,37376,68610,1150,808,1341,22100,10880,724,20,411.0,74.0,505
76,137893,Photo,1,11,3,2,0.0,1228,2392,17,17,19,2392,1228,17,0,0.0,0.0,0
77,137177,Photo,1,11,1,10,0.0,22984,59040,438,374,542,12716,4968,262,4,85.0,8.0,97
78,137177,Photo,2,11,1,3,0.0,1445,2774,217,167,211,1924,1005,154,0,56.0,8.0,64
79,137177,Photo,1,11,7,12,0.0,3754,8533,658,640,2085,6838,3224,598,2,29.0,7.0,38
80,137177,Status,2,11,7,3,0.0,8728,17827,2295,2235,2828,15418,7344,2099,2,86.0,13.0,101
81,137177,Photo,3,11,6,10,0.0,5990,11123,657,361,512,5057,2628,428,18,370.0,53.0,441
82,137177,Photo,1,11,6,3,0.0,4582,9193,454,306,431,3691,1722,305,5,190.0,57.0,252
83,137177,Photo,3,11,5,10,1.0,2938,5799,321,243,379,3668,1848,236,2,101.0,19.0,122
84,137177,Status,3,11,5,2,0.0,6692,13092,199,108,141,7549,3336,156,2,99.0,16.0,117
85,137177,Photo,1,11,4,9,1.0,2566,5244,384,280,469,3834,1806,266,10,140.0,8.0,158
86,137177,Link,1,11,4,3,0.0,21176,54779,330,228,329,13858,5248,185,2,130.0,31.0,163
87,137177,Photo,3,11,3,10,0.0,4012,7955,550,319,477,4625,2218,403,3,270.0,38.0,311
88,137177,Photo,1,11,3,3,0.0,1531,2838,212,189,1359,1210,690,143,3,30.0,6.0,39
89,137059,Photo,1,11,2,11,1.0,2938,6056,374,283,483,4509,2078,287,2,107.0,17.0,126
90,137059,Photo,1,11,2,3,0.0,24720,37240,845,564,850,14475,8120,504,13,331.0,77.0,421
91,137059,Photo,2,11,1,9,0.0,2219,4545,287,220,329,3189,1495,221,0,78.0,13.0,91
92,137059,Photo,3,11,1,3,0.0,4732,9303,607,352,518,6201,3136,445,9,301.0,32.0,342
93,137059,Photo,3,11,7,9,0.0,2225,4239,310,216,289,2570,1389,233,2,111.0,16.0,129
94,137059,Photo,2,11,7,4,0.0,2626,4943,316,213,299,3047,1605,244,2,124.0,22.0,148